<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="jravier" />


<title>Reproducible Research: Peer Assessment 1</title>

<script src="PA1_template_files/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="PA1_template_files/bootstrap-3.3.5/css/sandstone.min.css" rel="stylesheet" />
<script src="PA1_template_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="PA1_template_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="PA1_template_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="PA1_template_files/navigation-1.1/tabsets.js"></script>
<link href="PA1_template_files/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="PA1_template_files/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Reproducible Research: Peer Assessment 1</h1>
<h4 class="author">jravier</h4>
<h4 class="date">26/03/2020</h4>

</div>

<div id="TOC">
<ul>
<li><a href="#loading-and-preprocessing-the-data">Loading and preprocessing the data</a></li>
<li><a href="#what-is-mean-total-number-of-steps-taken-per-day">What is mean total number of steps taken per day?</a></li>
<li><a href="#what-is-the-average-daily-activity-pattern">What is the average daily activity pattern?</a></li>
<li><a href="#imputing-missing-values">Imputing missing values</a></li>
<li><a href="#are-there-differences-in-activity-patterns-between-weekdays-and-weekends">Are there differences in activity patterns between weekdays and weekends?</a></li>
</ul>
</div>

<div id="loading-and-preprocessing-the-data" class="section level2">
<h2>Loading and preprocessing the data</h2>
<p>Here is my code to load and transform the data.</p>
<p>Notice that I use the <code>read_csv</code> from <code>readr</code> package instead of the standard <code>read.csv</code>, which allow to:</p>
<ul>
<li>directly read from the zipped file inside the sip</li>
<li>assign right classes to columns (as seen from the output below)</li>
</ul>
<pre class="r"><code>library(readr)

activityDS&lt;-read_csv(&quot;activity.zip&quot;)</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   steps = col_double(),
##   date = col_date(format = &quot;&quot;),
##   interval = col_double()
## )</code></pre>
</div>
<div id="what-is-mean-total-number-of-steps-taken-per-day" class="section level2">
<h2>What is mean total number of steps taken per day?</h2>
<p>(Use <code>dplyr</code> package to calculate the total number of steps taken per day).</p>
<pre class="r"><code>library(dplyr)</code></pre>
<div id="make-a-histogram-of-the-total-number-of-steps-taken-each-day" class="section level4">
<h4>Make a histogram of the total number of steps taken each day:</h4>
<pre class="r"><code>actiStats&lt;-group_by(activityDS, date) %&gt;%
    summarise(steps=sum(steps, na.rm = TRUE))

hist(actiStats$steps, 
     main = &quot;number of steps taken each day (histogram)&quot;,
     xlab = &quot;number of steps&quot;,
     ylab = &quot;number of days&quot;)</code></pre>
<p><img src="figure/histogram_total_steps_per_day-1.png" /><!-- --></p>
</div>
<div id="mean-and-median-of-the-number-of-steps-taken-per-day" class="section level4">
<h4>Mean and median of the number of steps taken per day</h4>
<pre class="r"><code>c(&quot;mean&quot;=mean(actiStats$steps), &quot;median&quot;=median(actiStats$steps))</code></pre>
<pre><code>##     mean   median 
##  9354.23 10395.00</code></pre>
</div>
</div>
<div id="what-is-the-average-daily-activity-pattern" class="section level2">
<h2>What is the average daily activity pattern?</h2>
<p>We know that the intervals are 5 minutes apart, but what is the format of that variable?</p>
<pre class="r"><code>summary(activityDS$interval)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##     0.0   588.8  1177.5  1177.5  1766.2  2355.0</code></pre>
<pre class="r"><code>head(activityDS$interval, 40)</code></pre>
<pre><code>##  [1]   0   5  10  15  20  25  30  35  40  45  50  55 100 105 110 115 120 125 130
## [20] 135 140 145 150 155 200 205 210 215 220 225 230 235 240 245 250 255 300 305
## [39] 310 315</code></pre>
<pre class="r"><code>tail(activityDS$interval, 40)</code></pre>
<pre><code>##  [1] 2040 2045 2050 2055 2100 2105 2110 2115 2120 2125 2130 2135 2140 2145 2150
## [16] 2155 2200 2205 2210 2215 2220 2225 2230 2235 2240 2245 2250 2255 2300 2305
## [31] 2310 2315 2320 2325 2330 2335 2340 2345 2350 2355</code></pre>
<p>The <code>interval</code> variable is an integer going from 0 to 2355.<br />
It looks like the (1 or) 2 left most digit(s) in it are the hour of the day and the 2 rightmost are the minutes (see how the next values after each xx55 is yy00 and not xx60?).<br />
Which would mean that in fact, it is a time, going from 00:00 to 23:55</p>
<p>Lets check it:</p>
<pre class="r"><code>hist(activityDS$interval, breaks = seq(0, 2400, by=5)-1, xaxt = &quot;n&quot;, cex = 0.2,
     xlab = &quot;interval/100&quot;, 
     ylab = &quot;number of days&quot;,
     main = &quot;distribution of the intervals (histogram)&quot;)

axis(1, at = seq(0, 2400, by=100), labels = seq(0, 2400, by=100)/100)</code></pre>
<p><img src="figure/(not_asked)_interval_histo-1.png" /><!-- --></p>
<p>OK, so what we saw with <code>head</code> and <code>tail</code> is consistent across the whole data set.</p>
<p>Now we know how to make nice time series:</p>
<ul>
<li>We convert interval into time (using the formatC function followed by a regexp)</li>
<li>We don’t add to it the date variable, since we want an average daily activity pattern across all days. So the date has to be the same for every observation. We just taking today’s date (it won’t be displayed anyway).</li>
<li>(We are still removing NAs here)</li>
</ul>
<pre class="r"><code>actiPatt&lt;-group_by(activityDS, time = as.POSIXct(sub(&quot;(\\d{2})(\\d{2})&quot;, &quot;\\1:\\2&quot;, 
                                                formatC(activityDS$interval, 
                                                        width = 4, flag = &quot;0&quot;)), 
                                            format=&quot;%H:%M&quot;)) %&gt;%
    summarise(steps=mean(steps, na.rm = TRUE))

plot(x=actiPatt$time, y=actiPatt$steps, type=&quot;l&quot;,
     xlab = &quot;time of the day&quot;, 
     ylab = &quot;average number of steps&quot;,
     main = &quot;average daily activity pattern&quot;)
abline(v=actiPatt[actiPatt$steps==max(actiPatt$steps), ]$time)</code></pre>
<p><img src="figure/average_daily_pattern-1.png" /><!-- --></p>
<p>If we had directly plotted intervals on a numeric x-axis, we would have seen plateaus for all the non existent intervals, for example interval values between 1155 and 1200 (8 non-existent intervals each hour).<br />
Plotting intervals on a time x-axis allow us to get rid of these plateaus and see the real time series.</p>
<div id="which-5-minute-interval-contains-the-maximum-number-of-steps" class="section level4">
<h4>Which 5-minute interval contains the maximum number of steps?</h4>
<p>On average across all the days in the data set, this interval looks to be a bit after 8:00 AM (See vertical line above).<br />
let’s pick-up the exact interval:</p>
<pre class="r"><code>c(&quot;maximum average activity at&quot; = as.character(actiPatt[actiPatt$steps==max(actiPatt$steps), ]$time, &quot;%H:%M&quot;))</code></pre>
<pre><code>## maximum average activity at 
##                     &quot;08:35&quot;</code></pre>
</div>
</div>
<div id="imputing-missing-values" class="section level2">
<h2>Imputing missing values</h2>
<div id="total-number-of-missing-values-in-the-data-set" class="section level4">
<h4>Total number of missing values in the data set</h4>
<p>First, lets look for the NAs:</p>
<pre class="r"><code>summary(activityDS)</code></pre>
<pre><code>##      steps             date               interval     
##  Min.   :  0.00   Min.   :2012-10-01   Min.   :   0.0  
##  1st Qu.:  0.00   1st Qu.:2012-10-16   1st Qu.: 588.8  
##  Median :  0.00   Median :2012-10-31   Median :1177.5  
##  Mean   : 37.38   Mean   :2012-10-31   Mean   :1177.5  
##  3rd Qu.: 12.00   3rd Qu.:2012-11-15   3rd Qu.:1766.2  
##  Max.   :806.00   Max.   :2012-11-30   Max.   :2355.0  
##  NA&#39;s   :2304</code></pre>
<p>So we have NAs only in the “steps” variable and their total number is 2304.</p>
<pre class="r"><code>c(&quot;proportion of NA&quot;=sum(is.na(activityDS$steps))/dim(activityDS)[1])</code></pre>
<pre><code>## proportion of NA 
##        0.1311475</code></pre>
<p>So 13% of the observations are NAs.</p>
<p>Let’s also check for any missing interval observations:</p>
<pre class="r"><code>actiCount&lt;-group_by(activityDS, date) %&gt;%
    summarise(intercount= n())

summary(actiCount$intercount)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##     288     288     288     288     288     288</code></pre>
<p>So no missing observation (24 hours x 12 intervals/hour = 288 intervals each day).</p>
</div>
<div id="strategy-for-filling-in-all-of-the-missing-values" class="section level4">
<h4>Strategy for filling in all of the missing values</h4>
<p>Lets first have a look at the distribution of NAs:</p>
<pre class="r"><code>actiNas&lt;-group_by(activityDS, date) %&gt;%
    summarise(Nas=sum(is.na(steps)))
hist(actiNas$Nas, breaks = nrow(actiNas), col=&quot;blue&quot;,
     xlab = &quot;number of NAs&quot;,
     ylab = &quot;number of days&quot;,
     main = &quot;Number of NAs per day (histogram)&quot;)</code></pre>
<p><img src="figure/(not_asked)_NA_distrib-1.png" /><!-- --></p>
<p>Hey ! we have only 2 values:</p>
<pre class="r"><code>unique(actiNas$Nas)</code></pre>
<pre><code>## [1] 288   0</code></pre>
<p>So this mean that we have only missing values for full days (288 intervals), but no missing values inside the other days.</p>
<p>How many missing day?</p>
<pre class="r"><code>nrow(actiNas[actiNas$Nas==288,])</code></pre>
<pre><code>## [1] 8</code></pre>
<pre class="r"><code>nrow(actiNas[actiNas$Nas==288,]) / nrow(actiNas)</code></pre>
<pre><code>## [1] 0.1311475</code></pre>
<p>Our 13% again, of course!</p>
<p>So what strategy?</p>
<p>We could replace those missing days by the average daily activity pattern calculated above, but this would be inventing data.<br />
Let’s just replace the missing values with 0 (which happens to be the same as replacing them with the mean/median for that day, since they are 0 as well…).</p>
</div>
<div id="new-data-set-with-the-missing-data-filled-in" class="section level4">
<h4>new data set with the missing data filled in</h4>
<pre class="r"><code>actiFilled&lt;-activityDS
actiFilled[is.na(actiFilled$steps),]$steps&lt;-0</code></pre>
</div>
<div id="new-histogram-with-the-missing-data-filled-in" class="section level4">
<h4>new histogram with the missing data filled in</h4>
<pre class="r"><code>actiNewStats&lt;-group_by(actiFilled, date) %&gt;%
    summarise(steps=sum(steps))

hist(actiNewStats$steps,
     main = &quot;number of steps taken each day (histogram)&quot;,
     sub = &quot;NAs replaced by daily average&quot;,
     xlab = &quot;number of steps&quot;)</code></pre>
<p><img src="figure/new_histogram_with_filled_NAs-1.png" /><!-- --></p>
</div>
<div id="new-mean-and-median-with-the-missing-data-filled-in" class="section level4">
<h4>new mean and median with the missing data filled in</h4>
<pre class="r"><code>c(&quot;new mean&quot;=mean(actiNewStats$steps), &quot;new median&quot;=median(actiNewStats$steps))</code></pre>
<pre><code>##   new mean new median 
##    9354.23   10395.00</code></pre>
<p>Let’ recall the old values with the NA removed:</p>
<pre class="r"><code>c(&quot;mean&quot;=mean(actiStats$steps), &quot;median&quot;=median(actiStats$steps))</code></pre>
<pre><code>##     mean   median 
##  9354.23 10395.00</code></pre>
<p>As expected, they are exactly the same: when we removed the NAs, the daily average were already 0 for the days full of NAS!<br />
This way, there is no impact on the estimates of the total daily number of steps.</p>
</div>
</div>
<div id="are-there-differences-in-activity-patterns-between-weekdays-and-weekends" class="section level2">
<h2>Are there differences in activity patterns between weekdays and weekends?</h2>
<div id="new-variable-indicating-whether-a-given-date-is-a-weekday-or-weekend-day" class="section level4">
<h4>New variable indicating whether a given date is a weekday or weekend day</h4>
<pre class="r"><code>actiFilled$day&lt;-factor(ifelse(format(actiFilled$date, format = &quot;%u&quot;) %in% c(6,7), 
                              &quot;weekend&quot;,
                              &quot;weekday&quot;))
summary(actiFilled$day)</code></pre>
<pre><code>## weekday weekend 
##   12960    4608</code></pre>
<p>(it’s easier and more international to use directly the day of the week as a numeral, starting with Monday = 1)</p>
</div>
<div id="make-a-panel-plot-containing-a-time-series-plot" class="section level4">
<h4>Make a panel plot containing a time series plot</h4>
<p>As before, we convert the interval values to time values before making the plot:</p>
<pre class="r"><code>actiPanel&lt;-group_by(actiFilled, 
                    day, 
                    time = as.POSIXct(sub(&quot;(\\d{2})(\\d{2})&quot;, &quot;\\1:\\2&quot;, 
                                          formatC(actiFilled$interval, 
                                                  width = 4, flag = &quot;0&quot;)), 
                                      format=&quot;%H:%M&quot;)) %&gt;%
  summarise(steps=mean(steps))</code></pre>
<p>Panel plot, using ggplot2:</p>
<pre class="r"><code>library(ggplot2)

g&lt;-ggplot(actiPanel, aes(x=time, y=steps)) +
  labs(title =&quot;average daily activity pattern&quot;, 
       x=&quot;time of the day&quot;,
       y = &quot;average number of steps&quot;) + 
  geom_line() +
  facet_grid(day ~ .) +
  scale_x_datetime(date_labels = &quot;%H:%M&quot;)
print(g)</code></pre>
<p><img src="figure/weekdays_panel_plot-1.png" /><!-- --></p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
